// packages/solid/src/index.ts
import { createSignal as createSolidSignal, getOwner, onCleanup } from "solid-js";
import {
  createFetchTransport,
  createLiveQuerySession,
  createLiveTransport,
  createNormalizedCache,
  createQuerySession,
  applyInvalidations,
  isInvalidationSpec,
  watchSignal,
  type AlienSignalReader,
  type Fetcher,
  type InvalidationInput,
  type LiveSubscriber,
  type MutationOperation,
  type NormalizedCache,
  type QuerySession,
  type QuerySessionConfig,
  type SelectionStep,
} from "@gqlens/core";

export interface QueryConfig extends Partial<QuerySessionConfig> {
  readonly endpoint?: string | undefined;
  readonly cache?: NormalizedCache | undefined;
  readonly fetcher?: Fetcher | undefined;
  readonly liveSubscriber?: LiveSubscriber | undefined;
  readonly closeLive?: (() => void) | undefined;
}

export interface SolidSessionState {
  readonly loading: () => boolean;
  readonly error: () => Error | null;
  readonly session: QuerySession;
  readonly cache: NormalizedCache;
  demand(root: string, steps: readonly SelectionStep[]): void;
  read<T>(sig: AlienSignalReader<T>): T;
}

interface MutationOptions {
  readonly optimistic?: ((cache: NormalizedCache) => void) | undefined;
  readonly invalidates?: readonly InvalidationInput[] | undefined;
}

const defaultEndpoint = "/graphql";

export function createQuery(config: QueryConfig = {}): SolidSessionState {
  const cache = config.cache ?? createNormalizedCache();
  const fetcher = config.fetcher ?? createFetchTransport(config.endpoint ?? defaultEndpoint);
  const session = createQuerySession(cache, fetcher, {
    policy: config.policy ?? "cache-and-network",
    ttl: config.ttl ?? 0,
    metadata: config.metadata,
  });
  const reader = createSolidReaderScope(session);

  if (getOwner()) {
    onCleanup(() => {
      reader.dispose();
    });
  }

  queueMicrotask(() => session.schedule());

  return {
    loading: () => reader.read(session.loading),
    error: () => reader.read(session.error),
    session,
    cache,
    demand: reader.demand,
    read: reader.read,
  };
}

export function createLiveQuery(config: QueryConfig = {}): SolidSessionState {
  const cache = config.cache ?? createNormalizedCache();
  const [subscribe, close] = resolveLiveTransport(config);
  const session = createLiveQuerySession(cache, subscribe, {
    policy: config.policy ?? "cache-and-network",
    ttl: config.ttl ?? 0,
    metadata: config.metadata,
  });
  const reader = createSolidReaderScope(session);

  if (getOwner()) {
    onCleanup(() => {
      reader.dispose();
      close();
    });
  }

  queueMicrotask(() => session.schedule());

  return {
    loading: () => reader.read(session.loading),
    error: () => reader.read(session.error),
    session,
    cache,
    demand: reader.demand,
    read: reader.read,
  };
}

function resolveLiveTransport(config: QueryConfig): readonly [LiveSubscriber, () => void] {
  if (config.liveSubscriber) {
    return [config.liveSubscriber, config.closeLive ?? noop];
  }
  return createLiveTransport(config.endpoint ?? defaultEndpoint);
}

const noop = (): void => undefined;

export function createMutation<TInput extends Record<string, unknown>, TData>(
  mutation: MutationSource<TInput, TData>,
  cache: NormalizedCache = createNormalizedCache(),
  fetcher: Fetcher = createFetchTransport(defaultEndpoint),
): (input: TInput & MutationOptions) => Promise<TData> {
  const mutationFn = mutationFunction(mutation, fetcher);
  return async (input: TInput & MutationOptions): Promise<TData> => {
    const snapshots = input.optimistic
      ? snapshotFields(cache, input.invalidates ?? [])
      : new Map<string, Record<string, unknown>>();
    input.optimistic?.(cache);

    try {
      const data = await mutationFn(input);
      if (input.invalidates && input.invalidates.length > 0) {
        applyInvalidations(cache, input.invalidates);
      }
      normalizeMutationResult(cache, data);
      return data;
    } catch (error) {
      rollback(cache, input.invalidates ?? [], snapshots);
      throw error;
    }
  };
}

function normalizeMutationResult(cache: NormalizedCache, data: unknown): void {
  if (isEntityObject(data)) {
    cache.normalize({ mutation: data });
    return;
  }
  cache.normalize((data ?? {}) as Record<string, unknown>);
}

function isEntityObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && "__typename" in value && "id" in value;
}

type MutationSource<TInput extends Record<string, unknown>, TData> =
  | ((input: TInput) => Promise<TData>)
  | MutationOperation<TInput, TData>;

function mutationFunction<TInput extends Record<string, unknown>, TData>(
  mutation: MutationSource<TInput, TData>,
  fetcher: Fetcher,
): (input: TInput) => Promise<TData> {
  if (typeof mutation === "function") {
    return mutation;
  }

  return async (input: TInput): Promise<TData> => {
    const data = (await fetcher({
      query: mutation.query,
      variables: mutation.variables(input),
      operationName: mutation.operationName,
      selections: [],
    })) as Record<string, unknown>;
    return (data[mutation.operationName] ?? data) as TData;
  };
}

interface SolidReaderScope {
  demand(root: string, steps: readonly SelectionStep[]): void;
  read<T>(sig: AlienSignalReader<T>): T;
  dispose(): void;
}

function createSolidReaderScope(session: QuerySession): SolidReaderScope {
  const reader = session.mount();
  const watched = new Map<
    AlienSignalReader,
    { readonly track: () => number; readonly stop: () => void }
  >();

  return {
    demand(root: string, steps: readonly SelectionStep[]): void {
      session.select(reader, { root, steps });
      session.schedule();
    },

    read<T>(sig: AlienSignalReader<T>): T {
      let watchedSignal = watched.get(sig);
      if (!watchedSignal) {
        const [track, bump] = createSolidSignal(0);
        watchedSignal = {
          track,
          stop: watchSignal(sig, () => bump((value) => value + 1)),
        };
        watched.set(sig, watchedSignal);
      }
      watchedSignal.track();
      return sig();
    },

    dispose(): void {
      for (const item of watched.values()) {
        item.stop();
      }
      watched.clear();
      session.unmount(reader);
    },
  };
}

function snapshotFields(
  cache: NormalizedCache,
  specs: readonly InvalidationInput[],
): Map<string, Record<string, unknown>> {
  const snapshots = new Map<string, Record<string, unknown>>();
  for (const spec of specs) {
    if (!isInvalidationSpec(spec)) {
      continue;
    }
    if (!spec.keys || spec.keys.length === 0) {
      continue;
    }
    const ref = cache.entity(spec.type, spec.id);
    const values: Record<string, unknown> = {};
    for (const key of spec.keys) {
      values[key] = cache.field(ref, key).sig();
    }
    snapshots.set(`${spec.type}:${spec.id}`, values);
  }
  return snapshots;
}

function rollback(
  cache: NormalizedCache,
  specs: readonly InvalidationInput[],
  snapshots: ReadonlyMap<string, Record<string, unknown>>,
): void {
  for (const spec of specs) {
    if (!isInvalidationSpec(spec)) {
      applyInvalidations(cache, [spec]);
      continue;
    }
    const ref = cache.entity(spec.type, spec.id);
    const snapshot = snapshots.get(`${spec.type}:${spec.id}`);
    if (snapshot && spec.keys) {
      for (const key of spec.keys) {
        cache.field(ref, key).sig(snapshot[key]);
      }
    } else {
      cache.invalidate(ref, spec.keys);
    }
  }
}

// packages/react/src/index.tsx
import {
  createContext,
  createElement,
  type ReactElement,
  type ReactNode,
  useCallback,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
} from "react";
import {
  createFetchTransport,
  createLiveQuerySession,
  createLiveTransport,
  createNormalizedCache,
  createQuerySession,
  applyInvalidations,
  isInvalidationSpec,
  selectionKey,
  watchSignal,
  type AlienSignalReader,
  type Fetcher,
  type InvalidationInput,
  type LiveSubscriber,
  type MutationOperation,
  type NormalizedCache,
  type QuerySession,
  type QuerySessionConfig,
  type PlannerMetadata,
  type SelectionPath,
  type SelectionStep,
} from "@gqlens/core";

export interface GQLensConfig {
  readonly endpoint?: string | undefined;
  readonly cache?: NormalizedCache | undefined;
  readonly fetcher?: Fetcher | undefined;
  readonly liveSubscriber?: LiveSubscriber | undefined;
  readonly closeLive?: (() => void) | undefined;
  readonly defaultPolicy?: QuerySessionConfig["policy"] | undefined;
  readonly defaultTTL?: number | undefined;
}

export interface SessionState {
  readonly loading: boolean;
  readonly error: Error | null;
  readonly session: QuerySession;
  readonly cache: NormalizedCache;
  demand(root: string, steps: readonly SelectionStep[]): void;
  read<T>(sig: AlienSignalReader<T>): T;
}

interface GQLensRuntime {
  readonly cache: NormalizedCache;
  readonly defaultPolicy: QuerySessionConfig["policy"] | undefined;
  readonly defaultTTL: number | undefined;
  readonly fetcher: Fetcher;
  session(config: QuerySessionConfig): QuerySession;
  liveSession(config: QuerySessionConfig): QuerySession;
  invalidate(specs: readonly InvalidationInput[]): void;
}

const ConfigContext = createContext<GQLensRuntime | null>(null);
let nextMetadataId = 0;
const metadataIds = new WeakMap<PlannerMetadata, number>();
const defaultEndpoint = "/graphql";

export function GQLensProvider(props: {
  readonly config: GQLensConfig;
  readonly children: ReactNode;
}): ReactElement {
  const cache = useMemo(() => props.config.cache ?? createNormalizedCache(), [props.config.cache]);
  const fetcher = useMemo(
    () => props.config.fetcher ?? createFetchTransport(props.config.endpoint ?? defaultEndpoint),
    [props.config.fetcher, props.config.endpoint],
  );
  const [subscribe, closeLive] = useLiveTransportConfig(props.config);
  const runtime = useMemo<GQLensRuntime>(() => {
    const sessions = new Map<string, QuerySession>();
    const liveSessions = new Map<string, QuerySession>();
    return {
      cache,
      defaultPolicy: props.config.defaultPolicy,
      defaultTTL: props.config.defaultTTL,
      fetcher,

      session(config: QuerySessionConfig): QuerySession {
        return getOrCreateSession(sessions, cache, fetcher, config);
      },

      liveSession(config: QuerySessionConfig): QuerySession {
        return getOrCreateLiveSession(liveSessions, cache, subscribe, config);
      },

      invalidate(specs: readonly InvalidationInput[]): void {
        applyInvalidations(cache, specs);
        for (const session of sessions.values()) {
          session.refetch();
        }
        for (const session of liveSessions.values()) {
          session.refetch();
        }
      },
    };
  }, [cache, fetcher, props.config.defaultPolicy, props.config.defaultTTL, subscribe]);

  useEffect(() => closeLive, [closeLive]);

  return createElement(ConfigContext.Provider, { value: runtime }, props.children);
}

function useLiveTransportConfig(config: GQLensConfig): readonly [LiveSubscriber, () => void] {
  return useMemo(() => {
    if (config.liveSubscriber) {
      return [config.liveSubscriber, config.closeLive ?? noop] as const;
    }
    return createLiveTransport(config.endpoint ?? defaultEndpoint);
  }, [config.closeLive, config.endpoint, config.liveSubscriber]);
}

const noop = (): void => undefined;

export function useGQLensSession(config?: Partial<QuerySessionConfig>): SessionState {
  const global = useConfig();
  const policy = config?.policy ?? global.defaultPolicy ?? "cache-and-network";
  const ttl = config?.ttl ?? global.defaultTTL ?? 0;
  const metadata = config?.metadata;
  const session = useMemo(
    () => global.session({ policy, ttl, metadata }),
    [global, metadata, policy, ttl],
  );

  const reader = useRenderTracking(session);

  return {
    get loading() {
      return reader.read(session.loading);
    },
    get error() {
      return reader.read(session.error);
    },
    session,
    cache: global.cache,
    demand: reader.demand,
    read: reader.read,
  };
}

export function useLiveGQLensSession(config?: Partial<QuerySessionConfig>): SessionState {
  const global = useConfig();
  const policy = config?.policy ?? global.defaultPolicy ?? "cache-and-network";
  const ttl = config?.ttl ?? global.defaultTTL ?? 0;
  const metadata = config?.metadata;
  const session = useMemo(
    () => global.liveSession({ policy, ttl, metadata }),
    [global, metadata, policy, ttl],
  );

  const reader = useRenderTracking(session);

  return {
    get loading() {
      return reader.read(session.loading);
    },
    get error() {
      return reader.read(session.error);
    },
    session,
    cache: global.cache,
    demand: reader.demand,
    read: reader.read,
  };
}

export const useQuery: (config?: Partial<QuerySessionConfig>) => SessionState = useGQLensSession;
export const useLiveQuery: (config?: Partial<QuerySessionConfig>) => SessionState =
  useLiveGQLensSession;

export function useMutation<TInput extends Record<string, unknown>, TData>(
  mutation: MutationSource<TInput, TData>,
): (input: TInput & MutationOptions) => Promise<TData> {
  const global = useConfig();
  const mutationFn = useMemo(
    () => mutationFunction(mutation, global.fetcher),
    [global.fetcher, mutation],
  );

  return useCallback(
    async (input: TInput & MutationOptions): Promise<TData> =>
      runMutation(global.cache, mutationFn, input, global.invalidate),
    [global.cache, global.invalidate, mutationFn],
  );
}

function useConfig(): GQLensRuntime {
  const config = useContext(ConfigContext);
  if (!config) {
    throw new Error("GQLens hooks must be used within <GQLensProvider>");
  }
  return config;
}

function getOrCreateSession(
  sessions: Map<string, QuerySession>,
  cache: NormalizedCache,
  fetcher: Fetcher,
  config: QuerySessionConfig,
): QuerySession {
  const key = sessionKey(config);
  const existing = sessions.get(key);
  if (existing) {
    return existing;
  }

  const session = createQuerySession(cache, fetcher, config);
  sessions.set(key, session);
  return session;
}

function getOrCreateLiveSession(
  sessions: Map<string, QuerySession>,
  cache: NormalizedCache,
  subscribe: Parameters<typeof createLiveQuerySession>[1],
  config: QuerySessionConfig,
): QuerySession {
  const key = sessionKey(config);
  const existing = sessions.get(key);
  if (existing) {
    return existing;
  }

  const session = createLiveQuerySession(cache, subscribe, config);
  sessions.set(key, session);
  return session;
}

function sessionKey(config: QuerySessionConfig): string {
  return `${config.policy ?? ""}:${config.ttl ?? ""}:${metadataId(config.metadata)}`;
}

function metadataId(metadata: PlannerMetadata | undefined): number {
  if (!metadata) {
    return 0;
  }
  const existing = metadataIds.get(metadata);
  if (existing) {
    return existing;
  }
  const id = ++nextMetadataId;
  metadataIds.set(metadata, id);
  return id;
}

interface ReaderScope {
  demand(root: string, steps: readonly SelectionStep[]): void;
  read<T>(sig: AlienSignalReader<T>): T;
}

function useRenderTracking(session: QuerySession): ReaderScope {
  const reader = useMemo(() => session.mount(), [session]);
  const signalsRef = useRef<Set<AlienSignalReader>>(new Set());
  const pathsRef = useRef<SelectionPath[]>([]);
  const [, forceRender] = useReducer((value: number) => value + 1, 0);

  signalsRef.current = new Set<AlienSignalReader>();
  pathsRef.current = [];

  useLayoutEffect(() => {
    session.replace(reader, pathsRef.current);
    session.schedule();
    const unsubscribers = [...signalsRef.current].map((sig) => watchSignal(sig, forceRender));
    return () => {
      for (const unsubscribe of unsubscribers) {
        unsubscribe();
      }
    };
  });

  useEffect(
    () => () => {
      session.unmount(reader);
    },
    [reader, session],
  );

  return useMemo(
    () => ({
      demand(root: string, steps: readonly SelectionStep[]): void {
        addSelection(pathsRef.current, { root, steps });
      },
      read<T>(sig: AlienSignalReader<T>): T {
        signalsRef.current.add(sig);
        return sig();
      },
    }),
    [reader, session],
  );
}

function addSelection(paths: SelectionPath[], path: SelectionPath): void {
  const key = selectionKey(path);
  if (!paths.some((item) => selectionKey(item) === key)) {
    paths.push(path);
  }
}

interface MutationOptions {
  readonly optimistic?: ((cache: NormalizedCache) => void) | undefined;
  readonly invalidates?: readonly InvalidationInput[] | undefined;
}

type MutationSource<TInput extends Record<string, unknown>, TData> =
  | ((input: TInput) => Promise<TData>)
  | MutationOperation<TInput, TData>;

function mutationFunction<TInput extends Record<string, unknown>, TData>(
  mutation: MutationSource<TInput, TData>,
  fetcher: Fetcher,
): (input: TInput) => Promise<TData> {
  if (typeof mutation === "function") {
    return mutation;
  }

  return async (input: TInput): Promise<TData> => {
    const data = (await fetcher({
      query: mutation.query,
      variables: mutation.variables(input),
      operationName: mutation.operationName,
      selections: [],
    })) as Record<string, unknown>;
    return (data[mutation.operationName] ?? data) as TData;
  };
}

async function runMutation<TInput extends Record<string, unknown>, TData>(
  cache: NormalizedCache,
  mutationFn: (input: TInput) => Promise<TData>,
  input: TInput & MutationOptions,
  invalidate: (specs: readonly InvalidationInput[]) => void,
): Promise<TData> {
  const snapshots = input.optimistic
    ? snapshotFields(cache, input.invalidates ?? [])
    : new Map<string, Record<string, unknown>>();
  input.optimistic?.(cache);

  try {
    const data = await mutationFn(input);
    if (input.invalidates && input.invalidates.length > 0) {
      invalidate(input.invalidates);
    }
    normalizeMutationResult(cache, data);
    return data;
  } catch (error) {
    rollback(cache, input.invalidates ?? [], snapshots);
    throw error;
  }
}

function normalizeMutationResult(cache: NormalizedCache, data: unknown): void {
  if (isEntityObject(data)) {
    cache.normalize({ mutation: data });
    return;
  }
  cache.normalize((data ?? {}) as Record<string, unknown>);
}

function isEntityObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && "__typename" in value && "id" in value;
}

function snapshotFields(
  cache: NormalizedCache,
  specs: readonly InvalidationInput[],
): Map<string, Record<string, unknown>> {
  const snapshots = new Map<string, Record<string, unknown>>();
  for (const spec of specs) {
    if (!isInvalidationSpec(spec)) {
      continue;
    }
    if (!spec.keys || spec.keys.length === 0) {
      continue;
    }
    const ref = cache.entity(spec.type, spec.id);
    const fields: Record<string, unknown> = {};
    for (const key of spec.keys) {
      fields[key] = cache.field(ref, key).sig();
    }
    snapshots.set(`${spec.type}:${spec.id}`, fields);
  }
  return snapshots;
}

function rollback(
  cache: NormalizedCache,
  specs: readonly InvalidationInput[],
  snapshots: ReadonlyMap<string, Record<string, unknown>>,
): void {
  for (const spec of specs) {
    if (!isInvalidationSpec(spec)) {
      applyInvalidations(cache, [spec]);
      continue;
    }
    const ref = cache.entity(spec.type, spec.id);
    const snapshot = snapshots.get(`${spec.type}:${spec.id}`);
    if (snapshot && spec.keys) {
      for (const key of spec.keys) {
        cache.field(ref, key).sig(snapshot[key]);
      }
    } else {
      cache.invalidate(ref, spec.keys);
    }
  }
}
